# Generated by Selenium IDE
from logging import setLogRecordFactory
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLCVS():
  def __init__(self) -> None:
      self.setup_method()
      self.test_lCVS()


  def setup_method(self):
    self.driver = webdriver.Edge()
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_lCVS(self):
    self.driver.get("http://163.32.74.2/web_ap/student_allin/index.asp")
    self.driver.set_window_size(550, 692)
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.XPATH, "//input[@name=\'T1\']").click()
    self.driver.find_element(By.NAME, "T1").send_keys("s125687625")
    self.driver.find_element(By.CSS_SELECTOR, "td tr:nth-child(3) > td").click()
    self.driver.find_element(By.NAME, "T2").click()
    self.driver.find_element(By.NAME, "T2").send_keys("930110")
    self.driver.find_element(By.NAME, "B1").click()
    self.driver.find_element(By.NAME, "B21").click()
    self.driver.switch_to.default_content()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.NAME, "B1").click()
  

if __name__ == "__main__":
  test = TestLCVS()